name = "AoC2025"
uuid = "bf39e083-63e7-4b29-8cbc-96329322e560"
version = "0.1.0"
authors = ["Jakob Nybo Andersen <jakobnybonissen@gmail.com>"]

[deps]
BufferIO = "ff366017-094f-4144-bd70-a828a0d67152"
MemoryViews = "a791c907-b98b-4e44-8f4d-e4c2362c6b2f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
BufferIO = "0.2.2"
MemoryViews = "0.3.5"
Printf = "1.11.0"
StringViews = "1.3.6"
